name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    defaults:
      run:
        shell: bash
        working-directory: site


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages
      run: npm install && npm install -g npm-check
      
    - name: run linter
      run: npx eslint -c ./lint/.eslintrc.js "**/*.js"

    - name: check dependencies
      run: npm-check

    - run: npm build
    - run: npm test
