name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy
    - run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo test --verbose